### ISSUE TITLE
Create a flatpak package

### ISSUE THREAD

**Issue by eneshecan** [eneshecan/whatsapp-for-linux#11]

**Comment by ludvigng** [comment]
This would be very appreciated!

**Comment by Zorono** [comment]
any update on this, please ??

**Comment by Master811129** [comment]
please do this

**Comment by eneshecan** [comment]
Soon hopefully... However, I don't have much time lately and it would be really great for someone to at least take this package from my shoulders since I am maintaining plenty already.

**Comment by eneshecan** [comment]
So, thank you @ludvigng for taking care of this! There are a couple more things I will do soon to close this issue;
* Clean up the recipe a bit e.g. get the version from the generated file automatically, change app name etc.
* Integrate this package into our release cycle
* Make a PR on flathub to make the app available to users

**Comment by ludvigng** [comment]
And if anybody wants to test the flatpak, they can do so by downloading the manifest, installing flatpak-builder from their package manager and org.gnome.Sdk in flatpak, and then running `flatpak-builder --user --install build com.eneshecan.WhatsApp-For-Linux.yml` in the folder they downloaded the file to. This will download and build the dependencies specified in the manifest and then create and install the flatpak locally.

Like enes said, currently the icons aren't exported correctly, so the app won't have a proper launcher icon (nor a tray icon, not sure if that's because it's missing the icons or if I messed something up in regards to appindicator), but as far as I can tell it should work fine other than that. :)

**Comment by eneshecan** [comment]
Finally, the package took its place on https://github.com/flathub/com.github.eneshecan.WhatsAppForLinux and it will be on flathub soon. My sincere thanks to @ludvigng for initiating this!
