### ISSUE TITLE
switch to libayatana-appindicator

### ISSUE THREAD

**Issue by fvcr** [eneshecan/whatsapp-for-linux#143]
Hello,

I noticed that libappindicator was [removed](https://tracker.debian.org/news/1257945/removed-0492-8-from-unstable/) from the Debian archive.
Alternatively, switch for [libayatana-appindicator](https://tracker.debian.org/pkg/libayatana-appindicator).

Thanks.

**Comment by eneshecan** [comment]
We additionally should add gst-plugin dependencies to the deb package.

**Comment by floppywhisk** [comment]
update: libappindicator is by now only available in stretch and buster, so the workaround from #114 is not applicable anymore

**Comment by eneshecan** [comment]
> update: libappindicator is by now only available in stretch and buster, so the workaround from #114 is not applicable anymore

Yes, we should definitely switch to it. Last time I've tried to install the `libayatana-appindicator` package from arch linux repository, I got some errors but will try again. Anyone feel interested, please don't hesitate to do this;
* Change the reference in cmake
* Probably we won't need to change the code since the api is the same
* Change the reference in packages (snap, debian, appimage)

**Comment by drizzt** [comment]
Can you please revert this, since on Fedora libayatana-appindicator is not available?
