### ISSUE TITLE
Show/Hide window by shortcut

### ISSUE THREAD

**Issue by AlpSha** [eneshecan/whatsapp-for-linux#144]
I want to use this app by hiding its headers. But when I do that, I can't minimize it without activating headers back. 

It would be pretty good to have a shortcut to show/hide app window like in this Todoist application. https://github.com/KryDos/todoist-linux

**Comment by eneshecan** [comment]
Hi @AlpSha, thanks for opening an issue! Honestly, this is not feasible to implement since that is the responsibility of DE/WM and it might conflict with how the system behaves. If someone wants to use use it, one should enable the header bar. However, of course, if the majority wants this feature, we can implement it. We just need some thoughts from other users too, as a result, I will keep the issue open for now.
