### ISSUE TITLE
1.3.0 snap won't start

### ISSUE THREAD

**Issue by tom-james-watson** [eneshecan/whatsapp-for-linux#146]
**Description**

The app doesn't start when I launch it. Running from the command line, I see the following:

```
~ > whatsapp-for-linux
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
/snap/whatsapp-for-linux/27/bin/whatsapp-for-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

**To Reproduce**

```
sudo snap remove --purge whatsapp-for-linux
sudo snap install whatsapp-for-linux
whatsapp-for-linux
```

**Environment**
 - Ubuntu 21.10
 - snap
 - Gnome

**Comment by tom-james-watson** [comment]
I've just tried the deb and it works without issue.

**Comment by eneshecan** [comment]
Looks like an upstream issue https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715/61. Looking into it.

**Comment by eneshecan** [comment]
I couldn't reproduce the problem since I don't have an nvidia card. I guess we'll have to wait for the snap team to fix this.

**Comment by eneshecan** [comment]
> I've just tried the deb and it works without issue.
> 
> EDIT - I take that back. The deb starts but it becomes responsive when I try to actually scan the QR. I guess one thing at a time though - let's concentrate on the original issue.

The same happened to me but it worked on the second try opening the app. I couldn't see any logs or weird behaviour that might relate to a bug on our side.

**Comment by tom-james-watson** [comment]
OK, thanks - will just wait for upstream fix 👍

**Comment by upkeihas** [comment]
The same issue with snap happens to me too, but I can't get even the deb version working anymore. Not even the older 1.2.1 version. It used to work until yesterday when I had to reinstall my Xubuntu 21.10, but now as I try reading the QR code nothing seems to happen. But something DOES happen behind the scenes as whatsapp on my phone now tells me I have a new linked device so that part seems to be working ok. Still can't use the app though. The window just goes blank if I press any buttons, and pressing the refresh button just throws me back to the link device QR code view.

**Comment by tom-james-watson** [comment]
I saw exactly the same behaviour with the deb.

**Comment by markvollan** [comment]
just ensure that snapd.apparmor is enabled

on terminal enter: 
service snapd.apparmor start
whatsapp-for-linux
