### ISSUE TITLE
Create an AUR package

### ISSUE THREAD

**Issue by ltadeu6** [eneshecan/whatsapp-for-linux#42]
I found about this project on the [AUR](https://aur.archlinux.org/packages/whatsapp-for-linux/) but it is out of date, It would be easier for the project owner to maintain the package up to date there.

**Comment by ltadeu6** [comment]
the only thing needed to do is update a file like this https://aur.archlinux.org/whatsapp-for-linux.git

**Comment by eneshecan** [comment]
Hi, yes, that would be nice to have it here and have the maintainer to upload the package to the same repo because it's easier for me to have someone managing some package. Also, I see some small mistakes in that package like using debug version, not using `make install` command, not getting the version from autogenerated file etc. Let's try to contact them and try to cooperate on this. It would be nice if they are reading this :)

**Comment by juxuanu** [comment]
Today I noticed it is no longer in the AUR. 
Have you contacted him? Are you going to replace it?

**Comment by eneshecan** [comment]
I also saw that he removed it. Yeah, I will create a solid package since I switched to arch linux recently :)
